# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 11) do

  create_table "attendees", :force => true do |t|
    t.column "user_id",    :integer
    t.column "event_id",   :integer
    t.column "created_at", :datetime, :null => false
  end

  create_table "blogs", :force => true do |t|
    t.column "title",       :string,   :limit => 128, :default => "", :null => false
    t.column "description", :text
    t.column "created_at",  :datetime,                                :null => false
    t.column "modified_at", :datetime
    t.column "user_id",     :integer,                                 :null => false
  end

  create_table "categories", :force => true do |t|
    t.column "name",     :string,  :limit => 128, :default => "", :null => false
    t.column "short",    :string,  :limit => 32,  :default => "", :null => false
    t.column "ordering", :integer,                                :null => false
  end

  create_table "comments", :force => true do |t|
    t.column "title",            :string,   :limit => 50, :default => ""
    t.column "comment",          :string,                 :default => ""
    t.column "created_at",       :datetime,                               :null => false
    t.column "commentable_id",   :integer,                :default => 0,  :null => false
    t.column "commentable_type", :string,   :limit => 15, :default => "", :null => false
    t.column "user_id",          :integer,                :default => 0,  :null => false
  end

  add_index "comments", ["user_id"], :name => "fk_comments_user"

  create_table "events", :force => true do |t|
    t.column "title",         :string,   :limit => 128, :default => "", :null => false
    t.column "description",   :text
    t.column "date_start",    :datetime,                                :null => false
    t.column "date_end",      :datetime
    t.column "date_created",  :datetime,                                :null => false
    t.column "date_modified", :datetime
    t.column "user_id",       :integer,                                 :null => false
    t.column "location_id",   :integer,                                 :null => false
    t.column "category_id",   :integer
    t.column "popularity",    :integer,                 :default => 0,  :null => false
  end

  create_table "globalize_countries", :force => true do |t|
    t.column "code",                   :string, :limit => 2
    t.column "english_name",           :string
    t.column "date_format",            :string
    t.column "currency_format",        :string
    t.column "currency_code",          :string, :limit => 3
    t.column "thousands_sep",          :string, :limit => 2
    t.column "decimal_sep",            :string, :limit => 2
    t.column "currency_decimal_sep",   :string, :limit => 2
    t.column "number_grouping_scheme", :string
  end

  add_index "globalize_countries", ["code"], :name => "index_globalize_countries_on_code"

  create_table "globalize_languages", :force => true do |t|
    t.column "iso_639_1",             :string,  :limit => 2
    t.column "iso_639_2",             :string,  :limit => 3
    t.column "iso_639_3",             :string,  :limit => 3
    t.column "rfc_3066",              :string
    t.column "english_name",          :string
    t.column "english_name_locale",   :string
    t.column "english_name_modifier", :string
    t.column "native_name",           :string
    t.column "native_name_locale",    :string
    t.column "native_name_modifier",  :string
    t.column "macro_language",        :boolean
    t.column "direction",             :string
    t.column "pluralization",         :string
    t.column "scope",                 :string,  :limit => 1
  end

  add_index "globalize_languages", ["iso_639_1"], :name => "index_globalize_languages_on_iso_639_1"
  add_index "globalize_languages", ["iso_639_2"], :name => "index_globalize_languages_on_iso_639_2"
  add_index "globalize_languages", ["iso_639_3"], :name => "index_globalize_languages_on_iso_639_3"
  add_index "globalize_languages", ["rfc_3066"], :name => "index_globalize_languages_on_rfc_3066"

  create_table "globalize_translations", :force => true do |t|
    t.column "type",                :string
    t.column "tr_key",              :string
    t.column "table_name",          :string
    t.column "item_id",             :integer
    t.column "facet",               :string
    t.column "built_in",            :boolean, :default => true
    t.column "language_id",         :integer
    t.column "pluralization_index", :integer
    t.column "text",                :text
    t.column "namespace",           :string
  end

  add_index "globalize_translations", ["tr_key", "language_id"], :name => "index_globalize_translations_on_tr_key_and_language_id"
  add_index "globalize_translations", ["table_name", "item_id", "language_id"], :name => "globalize_translations_table_name_and_item_and_language"

  create_table "locations", :force => true do |t|
    t.column "name",        :string,  :limit => 128,                                 :default => "", :null => false
    t.column "street",      :string,  :limit => 128
    t.column "zip",         :string,  :limit => 10
    t.column "url",         :string
    t.column "email",       :string
    t.column "description", :text
    t.column "phone",       :string,  :limit => 128
    t.column "metro_id",    :integer,                                                                :null => false
    t.column "lat",         :decimal,                :precision => 15, :scale => 10
    t.column "lng",         :decimal,                :precision => 15, :scale => 10
  end

  create_table "metros", :force => true do |t|
    t.column "name",    :string, :limit => 128, :default => "", :null => false
    t.column "state",   :string, :limit => 128, :default => "", :null => false
    t.column "country", :string, :limit => 128, :default => "", :null => false
  end

  create_table "users", :force => true do |t|
    t.column "login",            :string,   :limit => 80,  :default => "",    :null => false
    t.column "password",         :string,   :limit => 40,  :default => "",    :null => false
    t.column "firstname",        :string,   :limit => 128
    t.column "name",             :string,   :limit => 128
    t.column "email",            :string,                  :default => "",    :null => false
    t.column "url",              :string
    t.column "avatar_url",       :string
    t.column "date_created",     :datetime,                                   :null => false
    t.column "last_login",       :datetime,                                   :null => false
    t.column "number_of_logins", :integer,                                    :null => false
    t.column "time_zone",        :string,   :limit => 128, :default => "UTC", :null => false
  end

end
